version: '3'

services:

    nginx:
        image: nginx:${NGINX_VERSION}-alpine
        ports:
            - "${SAMEGAME_MY_SERVER_PORT}:80"
            - "${SUPPORT_SERVER_PORT}:28080"
        volumes:
            - ${APP_DIR}:/var/www/html
            - ${SUPPORT_DIR}:/var/www/support-tool
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/support-tool.conf:/etc/nginx/conf.d/support-tool.conf
            - php-fpm-socket:/var/run/php-fpm
            - php-fpm-socket_support:/var/run/php-fpm_support
        depends_on:
            - samegame
            - support
            - db
            - redis
    samegame:
        build:
            context: ./docker/php
            args:
                - PHP_FPM_VERSION=${SAMEGAME_PHP_VERSION}
        ports:
            - 9000:9000
        volumes:
            - ${APP_DIR}:/var/www/html
            - php-fpm-socket:/var/run/php-fpm
        environment:
            MYSQL_USER:     ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MEMCACHED_PORT: ${MEMCACHED_PORT}
            DATABASE_HOST:  ${DATABASE_HOST}
            REDIS_PORT:     ${REDIS_PORT}
            MY_SERVER_HOST: ${SAMEGAME_MY_SERVER_HOST}
            MY_SERVER_PORT: ${SAMEGAME_MY_SERVER_PORT}
    support:
        build:
            context: ./docker/support-php
            args:
                - PHP_FPM_VERSION=${SUPPORT_PHP_VERSION}
        ports:
            - 29000:29000
        volumes:
            - ${SUPPORT_DIR}:/var/www/support-tool
            - php-fpm-socket_support:/var/run/php-fpm_support
        environment:
            MYSQL_USER:     ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MEMCACHED_PORT: ${MEMCACHED_PORT}
            REDIS_PORT:     ${REDIS_PORT}
    db:
        build:
            context: ./docker/mysql
            args:
                - MYSQL_VERSION=${MYSQL_VERSION}
        ports:
            - 13306:3306
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    redis:
        image: redis:${REDIS_VERSION}-alpine
        volumes:
            - redis_data:/data
        ports:
            - "${REDIS_PORT}:6379"
        command: redis-server --appendonly yes
        restart: always
volumes:
    db_data:
    redis_data:
    php-fpm-socket:
    php-fpm-socket_support:
